### ISSUE TITLE
Error handling fallthrough

### ISSUE THREAD

**Issue by ti2m** [apigee-127/bagpipes#9]
Hi,
I have to say that the piping system is probably a great idea, it is quiet complicated to stay on top of what's going on though. I'm trying to upgrade an expressed base setup and I'm having various issues with error handling. First thing is that when my application crashes I don't want the error message to go to the client. I would seriously consider only enabling this in debug mode as I don't see that you would ever want that to leak to a client.

To avoid this I previously added an extra error handler at the end which caught all the errors. Worked fine, problem solved. However, if I do that now with bagpipes in place the handler doesn't trigger. I tried to implement a custom error handler through a fitting, but I don't now if this will actually catch all errors (wouldn't in express) and I even want the json_error_handler to be in place. Doing that I figured though that my extra error handler (called within the `SwaggerExpress.create` callback after `swaggerExpress.register`) triggers if I use a custom error handler fitting. It even triggers when I copy over the exact same code from `json_error_handler`. But I got it to work that way. 
I disabled CORS for testing and send a request from cross origin to see that security and validator handlers return `Will process: no`. I expected this to throw an error, which it might do, but my custom fittings afterwards try to process.

So this is basically what I mean, before with express I kind of knew what was going on at the top level, now I don' have a clue anymore what's being processed where. I maybe wouldn't mind if that was on a lower level, but as said before the API will face the public and is therefore a major security risk. 

Another example for the new complexity is e.g. passing something from a fitting to a controller. Before I loaded data after the validation passed in a custom handler, added it to res.locals and had it in the controllers. Not sure if that is possible with the new piping system, I got it to work by attaching data to the response as before, but it took time.

Don't get me wrong, I love swagger and it might be I'm just doing it all wrong or missing documentation, but it seems to be a lot more complicated then before. Right now my only option seems to be to downgrade.

**Comment by theganyo** [comment]
Hey Tim,

I apologize for the confusion. It's almost certainly a lack of documentation on my part, so I really appreciate you working through this so I can improve it.

So there's a lot going on in you description and I'm not sure I'm getting it all, but I'll try to respond to what I think will help you:
1. If you use an `onError:` handler, it will catch all errors in the pipe after it is registered. This does have the effect (if you're using the included json_error_handler) of translating all errors to a JSON response instead of allowing the error to propagate. If you want to handle errors in a standard connect error handler, you can just disable it and register your error handler after the `swaggerExpress.register(app);` line in your app.js - just as you did before. (An alternative, of course, would be to write your own onError handler.)
2. Yes, you can absolutely attach whatever you want to the response as you did before. All your fitting would need to do is access context.response. It can be as simple as something like this:

``` javascript
module.exports = function init(fittingDef, pipes) {
  return function change_response(context, cb) {
    context.response.locals = { myData: true };
    cb();
  }
};
```

If that doesn't solve your issues yet or you have more questions, please keep this conversation going so I can improve things for you and those who come after you! :)

Scott

**Comment by ti2m** [comment]
Hi Scott,
thanks for the quick reply. It took me 3h as I thought the problem was in my setup, it seems though that the latest swagger-node-runner update (I assume the bagpipes update) causes my error handling issue. I created a minimal test case with the hello world example. 

```
'use strict';

var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // install middleware
  swaggerExpress.register(app);

  app.use(errorHandler);

  var port = process.env.PORT || 10010;
  app.listen(port);

  if (swaggerExpress.runner.swagger.paths['/hello']) {
    console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
  }
});


function errorHandler(err, req, res, next) {
  console.log('Extra error handler triggered.');
  if(err.failedValidation) {
    res.json({message: 'Validation failed.'});
  }
}
```

Then I create a validation error (I set the name parameter to required in the config). With the latest install my custom error handler doesn't trigger. I had an older version installed and it did work there (which caused the major confusion). I compared the two installations, swapped all npm module dirs and tracked it down to swagger-node-runner. I then saw that bagpipes was updated from 0.0.5 to 0.0.6. Maybe you can try to recreate the issue. From my point of view this is a critical regression as a potential attacker would be able to access the full stack trace in certain scenarios.

I haven't tracked down the CORS issue I ran into. If I disable CORS and trigger a cross orgin request, isn't the request suppose to fail, throw an error and not process on to the router? Just asking if I get this right and to make sure I'm not missing something in the concept.

**Comment by ti2m** [comment]
It's not bagpipes, it's the node runner due to the change in swagger-node-runner@2c0aac893606216eaff7bfc55c37495d0bb7ce6b. `context.error` gets deleted and therefore any additional error handler won't trigger. Was that intended???

**Comment by theganyo** [comment]
@ti2m Sorry for the confusion. Yes, this is intentional. If the json_error_handler handles the error, it deletes the error from the context so that it isn't handled again by a following handler. If you want to handle the error yourself, you'll want to remove the json_error_handler and install your own onError handler or, as you're doing, you may use a connect error handler.

As for the cors issue, are you using npm version 3? There is some kind of conflict with that and the cors handler. The quickest solution for now is to either remove the cors handler or use npm 2.x.
Scott

**Comment by theganyo** [comment]
@ti2m Follow up on the cors issue. The issue happens because npm3 now flattens everything as much as possible in the node_modules directory. Unfortunately, this causes a naming conflict between the cors module and the cors fitting of the same name. You can remove the conflict by changing your fittingsDirs property in config/default.yaml to remove node_modules. In other words, it should just look like this:

``` yaml
fittingsDirs: [ api/fittings ]
```

Because of this issue, I've also done the same for the templates on creating new projects in the swagger module.

**Comment by ti2m** [comment]
@theganyo I'll look into cors again and open another issue if I run into problems. Not using npm3 though and my major problem was that the OPTIONS request fell through although I expected an error to be thrown.

I got my error handling to work now. It took me quiet some time though to understand the internal workings. I personally think swallowing the error internally and returning it to the client is a really bad default for an API framework (e.g. compare just the latest blog by risingstack https://blog.risingstack.com/node-js-security-checklist/#errorhandling). With the latest update it got even harder to catch the error yourself as you now need to replace the error handler. Replacing is always a risky thing, so I prefer defaults being in place and then extending them somehow (which works great with the rest of swagger). Now I need to check with every swagger update if the default error handler has some kind of change that I need to be aware of, otherwise things might break. This is basically what has happened with the commit referenced above as my assumption about what swagger does and doesn't do weren't true anymore.

I got it now, so no problem here, only trying to clarify my issues with it in general as others might run into this as well. If things stay the way they are right now I think this definitely needs in depth documentation.

**Comment by theganyo** [comment]
>  I personally think swallowing the error internally and returning it to the client is a really bad default for an API framework

I don't disagree. That's a good note on the templates.

>  I prefer defaults being in place and then extending them somehow

That's fair, though potentially challenging to address. I think it would at least make sense to allow the user to enable/disable the unexpected exception handing (ie. the errors that get translated to 500). Is there anything else that you would you prefer to see?

**Comment by ti2m** [comment]
Thanks for your feedback, it is rare that suggestions are actually being considered. Enabling/disabling sounds like a great solution and should probably also be easy to document and for people to pick up. An option to disable the swallowing of the errors should also be a solution to my other error handling hack. I guess in general options make way more sense then overwriting something as options are easy to pass to bagpipes. One could then also use different configs for dev/prod. Sounds really good to me and am already happy with everything else!

**Comment by theganyo** [comment]
Ok. Here's what I'm looking at:
1. json_error_handler will no longer handle unexpected and 500 errors by default. Instead, it will pass them through to next(err).
2. Add a config to json_error_handler. If "handle500Errors: true", all errors will be handled and translated to json.

See: https://github.com/theganyo/swagger-node-runner/commit/fc450cbb9466fc73ab1d8f6ead2cac66ef8a1ca7

Thoughts?
